language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
addons:
  code_climate:
    repo_token: "e55c7b21ecb92332a55e3c8fe98821a8feaa3dc2ca9cb4f64f146e451762202c"
after_script:
  - codeclimate < coverage/lcov.info
  - gulp lint