language: node_js
node_js:
- '0.12'
addons:
  code_climate:
    repo_token: e55c7b21ecb92332a55e3c8fe98821a8feaa3dc2ca9cb4f64f146e451762202c
before_script:
- npm run lint
after_script:
- npm run publishToCodeclimate
deploy:
  provider: npm
  email: pavlov.valerii@gmail.com
  api_key:
    secure: T/KLkulRkf4OVovrtonasR1vfl40dQpp9XGj9HaUHwpkOP2UdMi97OK4JxuSKA1Uo4Ukx50i+nZtSH99aPr4Lmk/Zp7HubbGgcD9hy3aa5w0FQTBzYaB8G+3dFrnG1/2tJ6syH0tIx4YPSGHGRzpMjc61jn/gNLOCH2YiJZVLOg=
  on:
    tags: true
