language: node_js
node_js:
- '0.12'
addons:
  code_climate:
    repo_token: e55c7b21ecb92332a55e3c8fe98821a8feaa3dc2ca9cb4f64f146e451762202c
before_script:
- npm run lint
deploy:
  provider: npm
  email: pavlov.valerii@gmail.com
  api_key:
    secure: FFnSd17dPqUMbG2azmubkOpjRbnlmfes7LINE7M9stBG1fAqSZAyuukvQaKiWjLf/x4N6hYcbO6TRkBayhcHQVW5g+qT8I5eQu8IAYIaGfsAUWNwXwZv+TyvC1P2TVdZrrACxyZU2woFxOpVr6hewweETXLlBQ+fagPwpfRse4A=
  on:
    tags: true
